### ISSUE TITLE
Request: Accept also HDTV sub when file is 720p

### ISSUE THREAD

**Issue by TFMvdBroek** [bramwalet/Subliminal.bundle#15]
Say your file is 720p, but the subtitle sites only have a sub for HDTV (480p),
Would be nice if there was an option to also accept a subtitle of the same release group but other quality. Syncs are almost always the same, and in this way more hits are found.

**Comment by bramwalet** [comment]
Please contact Subliminal to implement this logic. 
This bundle will only use the latest version of Subliminal to search subtitles from Plex. The bundle cannot implement specific subtitle site behaviour. 

Once the feature is in place at Subliminal, let me know by raising an issue or file a pull request :)
