### ISSUE TITLE
Synology : Is there any way to start subliminal by command line

### ISSUE THREAD

**Issue by j3rrr3** [bramwalet/Subliminal.bundle#25]
Hi,

Is there any way to start a bulk search on my entire library by command line on plex (Synology)?

Thanks a lot in advance,
Jeremy.

**Comment by j3rrr3** [comment]
Sorry , it was a subtitles rating missmatch :-1:

**Comment by bramwalet** [comment]
Yes, see my comment in the Plex forums: https://forums.plex.tv/discussion/comment/683947/#Comment_683947

The best way I think there is, is to use Plex Media Scanner and schedule it to refresh a certain section of your library. See the article on the Plex website: https://support.plex.tv/hc/en-us/articles/201242707-Plex-Media-Scanner-via-Command-Line
