### ISSUE TITLE
Channel not showing in Plex

### ISSUE THREAD

**Issue by argash** [bramwalet/Subliminal.bundle#29]
I'm just getting started with this and I followed the install instructions and putting the .bundle file into the plugins foleder and after restarting Plex I do not see a channel for the bundle. Am I missing something?

**Comment by dny238** [comment]
Where are you looking? 

https://app.plex.tv/web/app#!/settings/server

Pick Agents on the Left
Pick TV Shows at the Top
Pick TheTVDB or another agent that's not personal media
Should be in the check list.

**Comment by argash** [comment]
ahhh found it, thank you, might I suggest an update to the readme to make that more clear?

**Comment by FezVrasta** [comment]
I can't find the configuration of this plugin... 

![image](https://cloud.githubusercontent.com/assets/5382443/17323394/590fdb24-58a2-11e6-8871-136fc6f1e864.png)

![image](https://cloud.githubusercontent.com/assets/5382443/17323404/5f5b70f6-58a2-11e6-967f-8634b3b46f95.png)

What am I doing wrong?
